### ISSUE TITLE
[BUG] Audio GUI Bug

### ISSUE THREAD

**Issue by Nicolasncg** [MafiaHub/Oakwood#1]
**Describe the bug**
There's a glitch when you change the Volume of "Sounds",it changes the same time at "Cars".

**To Reproduce**
1. Go to Audio Settings
2. Click on 'Sounds'
3. Scroll down to Left or Right
4. See that it changes both "Sounds" and "Cars"

**Expected behavior**
Basically when you scroll the mouse to adjust the volume of "Sounds" (left or right),it changes for "Cars" too.

**Screenshots**
https://media.discordapp.net/attachments/563748373996503060/593412654148747285/unknown.png?width=630&height=473.

**Specs (please complete the following information):**
 - OS: [Windows 8.1]
 - Game version [GOG]

**Comment by zaklaus** [comment]
Audio slider should scale the cars slider instead of overriding it.

**Comment by zaklaus** [comment]
Fixed!
