### ISSUE TITLE
[BUG] Players ped doesn't receive damage

### ISSUE THREAD

**Issue by DanielsToJa** [MafiaHub/Oakwood#23]
**Describe the bug**
While shooting to other player, he sometimes doesn't receive any damage, even when you see blood from PED. It isn't lag for sure. 

**Expected behavior**
Game should smoothly record hit scans (?)

**Specs (please complete the following information):**
 - OS:  Windows 10
 - Game version:  Steam

**Additional context**
It rarely happens, but when do irritates so much.

**Comment by zaklaus** [comment]
Client has been updated, requires further testing.
