### ISSUE TITLE
[BUG] Duplicating peds

### ISSUE THREAD

**Issue by DanielsToJa** [MafiaHub/Oakwood#24]
**Describe the bug**
Players ped is duplicating very often after teleportation, its client-side bug. Sometimes game duplicates model not once, but even twice or three times. 

**To Reproduce**
1. Join server with 2 launchers, one for testing, second for observation. 
2. Use command /tp, /tele, /kill as first player or just shoot each other.
3. Most of the time you will see duplicated ped when looking as one of players.

**Expected behavior**
Game shouldn't create any ped after teleportation.

**Screenshots**
https://media.discordapp.net/attachments/532441302764224520/622847276296962061/unknown.png?width=816&height=538

**Specs (please complete the following information):**
 - OS:  Windows 10
 - Game version: Steam

**Comment by inlife** [comment]
Fixed in `v1.21.8`
