### ISSUE TITLE
[BUG] Game badly register players death

### ISSUE THREAD

**Issue by DanielsToJa** [MafiaHub/Oakwood#27]
**Describe the bug**
When shooting to other player, sometimes you're "killing" him but game freezes his ped. You can see peds health bar, players nickname and model. It maybe related to crouching, because while testing, happened only when someone crouched. "Killed"player is invisible and didn't die exactly.

**To Reproduce**
1. Shoot other player when he's crouching
2. If bug don't happen do it again and again
3. Here is your result

**Expected behavior**
Game shouldn't freeze ped and shouldn't make player invisible.

**Screenshots**
https://www.youtube.com/watch?v=GIZUurBq9E4&feature=youtu.be&t=203

**Specs (please complete the following information):**
 - OS: Windows 10
 - Game version: Steam

**Comment by zaklaus** [comment]
Client has been updated, requires further testing.
