### ISSUE TITLE
[BUG] ALT TABBING

### ISSUE THREAD

**Issue by numero69** [MafiaHub/Oakwood#4]
**Describe the bug**
When I alt-tabbed out of the game and back, the game crashed with no message or dialog.

**To Reproduce**
Alt-tab out and back

**Expected behavior**
Continuing to play the game

**Specs (please complete the following information):**
 - OS: W10
 - Game version: GOG

**Temp fix**
- Use windowed mode

**Comment by zaklaus** [comment]
Possibly caused by #6 . Please, check it with the newest build now.
