### ISSUE TITLE
[BUG] Crash on re-connection

### ISSUE THREAD

**Issue by zaklaus** [MafiaHub/Oakwood#6]
**Describe the bug**
The game crashes sometimes when you re-connect to the server.

**To Reproduce**
1. Join a server
2. Leave it
3. Join it again
4. Crash!

**Expected behavior**
Crash shouldn't happen at all

**Specs (please complete the following information):**
 - OS: Windows 10
 - Game version: GOG

**Additional context**
Has to do something with `Vehicle::SetEngineOn` call

**Comment by inlife** [comment]
Regarded to fixed. In case issue re-appears, please reopen it.
