### ISSUE TITLE
[BUG] Crashing when the server is shut down

### ISSUE THREAD

**Issue by numero69** [MafiaHub/Oakwood#8]
**Describe the bug**
When the server is shut down or crashes, your game does as well.

**To Reproduce**
1. Admins shuts down the server
2. Your game crashes

**Expected behavior**
You are returned back to the main menu

**Specs (please complete the following information):**
 - OS: Windows 10
 - Game version GOG

**Comment by zaklaus** [comment]
Fixed in the latest build.
