### ISSUE TITLE
[BUG] Map squares not accurate

### ISSUE THREAD

**Issue by numero69** [MafiaHub/Oakwood#9]
**Describe the bug**
Player and car squares on the ingame map are not accurate, laggy, or do not update quick enough

**To Reproduce**
1. See map

**Expected behavior**
Showing the right position of players and cars

**Screenshots**

**Specs (please complete the following information):**
 -win10
 -gog
![GTDShPL](https://user-images.githubusercontent.com/26823803/60387945-daf33300-9aaa-11e9-98c7-e993b2bc7876.png)
![6QBt5Wu](https://user-images.githubusercontent.com/26823803/60387946-daf33300-9aaa-11e9-88b5-48bcb2f8b447.png)
![VrCSx09](https://user-images.githubusercontent.com/26823803/60387947-daf33300-9aaa-11e9-8f89-4a13d54c72ca.png)
![ebInHzL](https://user-images.githubusercontent.com/26823803/60387948-daf33300-9aaa-11e9-95ff-f9dbfec97540.png)
![KwvzhUO](https://user-images.githubusercontent.com/26823803/60387949-db8bc980-9aaa-11e9-931a-ae47c6996752.png)
![miG46Cu](https://user-images.githubusercontent.com/26823803/60387950-db8bc980-9aaa-11e9-9977-4a3c984239a8.png)

**Comment by zaklaus** [comment]
To be considered, we might get rid of game map in favor of online map resource in RC2
